release:
  github:
    owner: Siroshun09
    name: dljdk
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/dljdk/main.go
    binary: dljdk
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
